## For Assignment 1

### https://www.kaggle.com/uciml/pima-indians-diabetes-database - Download the indian diabetes dataset

1.Import relevant commands for numpy, pandas, sklearn.

In [16]:
#Import Libraries
import numpy as np
from pandas import DataFrame, read_csv, to_numeric
from sklearn import cluster
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics

2.Using the appropriate pandas function, read the diabetes.csv into a dataframe. Pay good attention to the necessary arguments.

In [17]:
data = read_csv('diabetes.csv', sep=",")
data.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [18]:
data.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,5,95,72,33,0,37.7,0.370,27,0
1,0,131,0,0,0,43.2,0.270,26,1
2,2,112,66,22,0,25.0,0.307,24,0
3,3,113,44,13,0,22.4,0.140,22,0
4,2,74,0,0,0,0.0,0.102,22,0

In [19]:
data.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

3.use naivebayes, logistic regression and 3-nn classifiers (library) to train on the training sets and 
compute training and validation errors for each fold (see the diabetes_10fold_train_val.zip file, XT01...XT10: training sets, XV01....XV10: corresponding validation sets). The target label is Outcome.

In [20]:
#Gaussian Classifier
gnb = GaussianNB()

#logistic regression classifier
lgr = LogisticRegression(random_state=0, max_iter=1000)

#knn classifier
knn   = KNeighborsClassifier(n_neighbors=3)


#find the mean at the end
mean_nb = 0
mean_lr=0
mean_nn=0
nb_valid_error=[]
lgr_valid_error=[]
knn_valid_error=[]

# list to store the file numbers
file_number = ['01','02','03','04','05','06','07','08','09','10']
# looping to calculate the error for each training set
for i in file_number:
    trainingSet = '/Users/STSC/Documents/Summer21/ML/HW1/diabetes_10fold_train_val/XT'+i+'.csv'
    XT = read_csv(trainingSet, sep=",")
    validationSet = '/Users/STSC/Documents/Summer21/ML/HW1/diabetes_10fold_train_val/XV'+i+'.csv'
    VT = read_csv(validationSet, sep=",")
    
    # Declaring input and output 
    X_train=XT.drop('Outcome', axis=1)
    Y_train=XT['Outcome']

    #Training the models
    gnb.fit(X_train, Y_train)
    logistic = lgr.fit(X_train, Y_train)
    fit   = knn.fit(X_train, Y_train)

    #predicting the training values
    XT_features =  XT.drop('Outcome', axis=1)
    y_pred_nb_train = gnb.predict(XT_features)
    y_pred_nn_train = fit.predict(XT_features)
    y_pred_lr_train = logistic.predict(XT_features)
    XT_label_train =  XT['Outcome']
    accuracy_nb_train = metrics.accuracy_score(XT_label_train, y_pred_nb_train)
    accuracy_lr_train = metrics.accuracy_score(XT_label_train, y_pred_lr_train)
    accuracy_nn_train = metrics.accuracy_score(XT_label_train, y_pred_nn_train)
    
    
    #Prediction for Validation files
    VT_features =  VT.drop('Outcome', axis=1)
    y_pred_nb = gnb.predict(VT_features)
    y_pred_nn = fit.predict(VT_features)
    y_pred_lr = logistic.predict(VT_features)
    VT_label =  VT['Outcome']
    accuracy_nb = metrics.accuracy_score(VT_label, y_pred_nb)
    accuracy_lr = metrics.accuracy_score(VT_label, y_pred_lr)
    accuracy_nn = metrics.accuracy_score(VT_label, y_pred_nn)
    nb_valid_error.append(1-accuracy_nb)
    lgr_valid_error.append(1-accuracy_lr)
    knn_valid_error.append(1-accuracy_nn)

    # Model Accuracy and Error
    print("\n Error values for set "+ i+ ": \n")
    print("NB: Validation Error: "  , 1 - accuracy_nb, "; Training Error: ", 1 - accuracy_nb_train)
    print("LR: Validation Error: "  , 1 - accuracy_lr, "; Training Error: ", 1 - accuracy_lr_train)
    print("NN: Validation Error: "  , 1 - accuracy_nn, "; Training Error: ", 1 - accuracy_nn_train)

 Error values for set 01:

NB: Validation Error:  0.21052631578947367 ; Training Error:  0.23699421965317924
LR: Validation Error:  0.21052631578947367 ; Training Error:  0.21820809248554918
NN: Validation Error:  0.2894736842105263 ; Training Error:  0.14884393063583812

 Error values for set 02:

NB: Validation Error:  0.2727272727272727 ; Training Error:  0.23444283646888564
LR: Validation Error:  0.23376623376623373 ; Training Error:  0.22141823444283648
NN: Validation Error:  0.4285714285714286 ; Training Error:  0.14616497829233

 Error values for set 03:

NB: Validation Error:  0.2727272727272727 ; Training Error:  0.23299565846599135
LR: Validation Error:  0.2987012987012987 ; Training Error:  0.2127351664254703
NN: Validation Error:  0.24675324675324672 ; Training Error:  0.1418234442836469

 Error values for set 04:

NB: Validation Error:  0.18181818181818177 ; Training Error:  0.2474674384949349
LR: Validation Error:  0.1298701298701299 ; Training Error:  0.22720694645441386
NN: Validation Error:  0.20779220779220775 ; Training Error:  0.15774240231548475

 Error values for set 05:

NB: Validation Error:  0.23376623376623373 ; Training Error:  0.2445730824891461
LR: Validation Error:  0.20779220779220775 ; Training Error:  0.21997105643994208
NN: Validation Error:  0.2987012987012987 ; Training Error:  0.13603473227206941

 Error values for set 06:

NB: Validation Error:  0.2727272727272727 ; Training Error:  0.23589001447178004
LR: Validation Error:  0.22077922077922074 ; Training Error:  0.2170767004341534
NN: Validation Error:  0.3246753246753247 ; Training Error:  0.15195369030390737

 Error values for set 07:

NB: Validation Error:  0.24675324675324672 ; Training Error:  0.24023154848046313
LR: Validation Error:  0.22077922077922074 ; Training Error:  0.21997105643994208
NN: Validation Error:  0.2597402597402597 ; Training Error:  0.16208393632416784

 Error values for set 08:

NB: Validation Error:  0.23376623376623373 ; Training Error:  0.23010130246020255
LR: Validation Error:  0.2597402597402597 ; Training Error:  0.2170767004341534
NN: Validation Error:  0.3246753246753247 ; Training Error:  0.13892908827785821

 Error values for set 09:

NB: Validation Error:  0.16883116883116878 ; Training Error:  0.2489146164978292
LR: Validation Error:  0.16883116883116878 ; Training Error:  0.22141823444283648
NN: Validation Error:  0.3116883116883117 ; Training Error:  0.1432706222865412

 Error values for set 10:

NB: Validation Error:  0.3157894736842105 ; Training Error:  0.22543352601156075
LR: Validation Error:  0.2894736842105263 ; Training Error:  0.21242774566473988
NN: Validation Error:  0.4078947368421053 ; Training Error:  0.14017341040462428

4.is the error of naive bayes <0.2 with confidence 0.9

In [21]:
# calculating average error from 10 sets
mean_nb=np.mean(nb_valid_error)
mean_lr=np.mean(lgr_valid_error)
mean_nn=np.mean(knn_valid_error)
print(mean_nb,mean_lr,mean_nn)
#Mean
m=np.mean(nb_valid_error)
print("Mean=",m)
#Standard Deviation
S=np.std(nb_valid_error)
print("Standard Deviation=",S)
#No of folds
k=10
#T test
Value=((k**0.5)*(m-0.2))/S
print("Value=",Value)

0.2409432672590567 0.22402597402597402 0.30999658236500344
Mean= 0.2409432672590567
Standard Deviation= 0.042884170171581644
Value= 3.0191555268432793

5.have  naive bayes and knn the same error?

6.do the three classifiers have different errors?

In [22]:
#Anova Test
df1=2
df2=27
df_total=29
number_of_folds=10
#from the F distribution table
f_crit=2.51061
logistic_mean=mean_lr
naive_mean=mean_nb
knn_mean=mean_nn
total_Mean=(logistic_mean+naive_mean+knn_mean)/3
print("Total Mean=",total_Mean)

0.258321941216678

In [23]:
#LogisticRegression
logreg_ss=[]
mean_diff=(logistic_mean-total_Mean)**2
for i in range(len(lgr_valid_error)):
    ss_within=(lgr_valid_error[i]-logistic_mean)**2
    logreg_ss.append(ss_within)
sst_logreg=mean_diff
logreg_ssw=sum(logreg_ss)

#NaiveBayes
naive_ss=[]
mean_diff=(naive_mean-total_Mean)**2
for i in range(len(nb_valid_error)):
    ss_within=(nb_valid_error[i]-naive_mean)**2
    naive_ss.append(ss_within)
sst_naive=mean_diff
naive_ssw=sum(naive_ss)

#Knn Classifier
knn_ss=[]
mean_diff=(knn_mean-total_Mean)**2
for i in range(len(knn_valid_error)):
    ss_within=(knn_valid_error[i]-knn_mean)**2
    knn_ss.append(ss_within)
sst_knn=mean_diff
knn_ssw=sum(knn_ss)
total_sst=sst_logreg+sst_naive+sst_knn
total_ssw=logreg_ssw+naive_ssw+knn_ssw
print('SST',total_sst)
print('SSW',total_ssw)

ssb_total=(logistic_mean-total_Mean)**2+(naive_mean-total_Mean)**2+(knn_mean-total_Mean)**2
ms_between=k*ssb_total/df1
ms_within=total_ssw/df2
F_value=ms_between/ms_within
print('F value',F_value)

SST 0.004148500211879357
SSW 0.08359711865103639
F value 6.699364016857416